name: Test PR Context

on:
  pull_request:
    types: 
      - closed
    branches:
      - "AK-48261-release-test"
    paths:
      - "clusters/services/*"
      - "clusters/prod.testing/services/*"

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo pr_title "$PR_TITLE"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
             **.ver

      - name: echo changed files
        id: echo_changed_files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo $ALL_CHANGED_FILES

      - name: Only run if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "PR was merged"

      - name: only run if PR title contains "Services Upgrade Request"
        if: contains(github.event.pull_request.title, 'Services Upgrade Request')
        run: echo "PR title contains 'Services Upgrade Request'"

      - name: only run if PR was merged and services upgrade request in title
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Services Upgrade Request')
        run: echo "PR was merged and PR title contains 'Services Upgrade Request'"
