name: Test PR Context

on:
  pull_request:
    types: [closed]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo pr_title "$PR_TITLE"
